# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 14:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='answers',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
